### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by noklam** [Galileo-Galilei/kedro-pandera#36]

**Comment by noklam** [comment]
@Galileo-Galilei I am not familiar with the release workflow, I saw there is a `prepare-release` workflow and seems like it bump version automatically. How does the release process work?

**Comment by Galileo-Galilei** [comment]
The release workflow works in 2-steps: 
- the prepare-release worklow which bumps the changelog and the version and opens a PR to enable manuel fixes at this step (eg. if the release notes are not up to date)

- Once the PR is merged, the deploy worklow creates a github release and deploy the main branch to PyPI

**Comment by Galileo-Galilei** [comment]
I'll do it tonight, for some unknown reason I cant trigger the workflow through the app.

**Comment by noklam** [comment]
@Galileo-Galilei I fixed a bug in the Github action but run into permission error. Maybe it has to be you running the workflow. https://github.com/Galileo-Galilei/kedro-pandera/actions/runs/6052281404/job/16425421416

**Comment by Galileo-Galilei** [comment]
I'll check this. I may have not enable / configured my PyPI and github tokens for this repo. I'll wait you to merge #32 before I'll make the release. 

Do you think that it is appropriate to make an announcement on the kedro slack to attract users or is this considered as too aggressive self promotion and reserved to the team for "official" products?

**Comment by noklam** [comment]
I think it's fine to do it on #plugin-integration channels, but probably better to announce by you to avoid people thinking this is from the official Kedro team.

**Comment by Galileo-Galilei** [comment]
[Done!](https://pypi.org/project/kedro-pandera/)

I close the issue but we may need to refactor the github action & advertise on the slack channel.
