### ISSUE TITLE
Add kedro~=0.19.0 compatability

### ISSUE THREAD

**Issue by mck-star-yar** [Galileo-Galilei/kedro-pandera#46]
## Description

This plugin's requirement has clipped kedro version `<0.19`. I'm using newer kedro version and would like to use this plugin with it.

**Comment by Galileo-Galilei** [comment]
Hi! Feel free to open a PR and I'll merge it immediately, or I'll do it tonight

**Comment by Galileo-Galilei** [comment]
Hi @mck-star-yar this is officially on PyPI, sorry for the delay!

Feel free to give feedback on the plugin and eventually features you'd like to see in the future.
