### ISSUE TITLE
Add a hello-world tutorial

### ISSUE THREAD

**Issue by Galileo-Galilei** [Galileo-Galilei/kedro-pandera#5]
## Description

Code to copy paste is worth a thousand word !

## Possible Implementation
- clone the pandas iris tutorial
- create the schema ``example_iris_data`` of a dataframe with the ``kedro pandera infer -d example_iris_data`` command.
- Add a manual validation in the schema (ex: check that target is in ["setosa", "versicolor", "virginica"]
- Run on a fake dataset
- Enjoy the failure message

## Other features
- use the CLI to see the schema
- generate a fake dataset and run the pipeline with it
- add extra configuration (lazy failure...)

**Comment by noklam** [comment]
I would like to know what features are expected to be develop? Do you expect user run the validation manually or automatically during a `kedro run`? via #10 + reading the corresponding configuration?
