### ISSUE TITLE
fix for kedro >= 0.19.0

### ISSUE THREAD

**Issue by mjspier** [Galileo-Galilei/kedro-pandera#54]
## Description
Kedro 0.19.0 had a breaking change. 
- Renamed data_set and DataSet to dataset and Dataset everywhere.

The current hook still references catalog._data_sets which does not work with kedro >= 0.19.0

## Steps to Reproduce
1. install kedro >= 0.19.0
2. install kedor-pandera <=0.2.0
3. create pandera schema and add to catalog.yaml
4. run kedro run

## Expected Result
Pipeline runs and validates dataset

## Actual Result
Pipeline does not run successfully and shows error

**Comment by mjspier** [comment]
https://github.com/Galileo-Galilei/kedro-pandera/pull/55 covers this issue

**Comment by Galileo-Galilei** [comment]
Closed by #55

**Comment by Galileo-Galilei** [comment]
It's on Pypi: https://pypi.org/project/kedro-pandera
